// GENERATED from the live API, then committed deliberately.
//
// The interests picker used to block a first launch on downloading the whole
// vocabulary: 1243 quote tags (~223 KB of JSON) plus 118 fact categories, over
// two requests, before it could show a single chip. Baking the list in makes
// that instant. interestOptions still refreshes from the API in the
// background and caches the result, so anything added on the backend shows up
// on the next launch without a new build - this list is the floor, not the
// ceiling.
//
// Order is significant and is NOT alphabetical. It reproduces exactly what
// interestOptions computes: quote tags sorted by quoteCount descending,
// interleaved with fact categories by each item's rank within its own group,
// then de-duplicated case-insensitively.
//
// Note the interleave is proportional, not alternating: there are 1243 tags to
// 118 categories, so rank i/n puts roughly ten tags near the top for every
// category. InterestsScreen's "Choose for me" takes the first
// UserInterests.autoPickCount (12) entries, which today is eleven quote tags
// and one fact category. Auto-picked users therefore get well-filtered quotes
// and only lightly filtered facts - worth revisiting if that reads as a bug
// rather than a consequence.
//
// To regenerate: fetch Tag/GetAllTags?getAllRows=true and
// Fact/GetAllAiFactCategories, then apply the merge above.

/// Every selectable interest, in popularity order. See file header.
const List<String> kDefaultInterestOptions = [
  'philosophy',
  'Languages',
  'life',
  'leadership',
  'innovation',
  'courage',
  'creativity',
  'freedom',
  'knowledge',
  'science',
  'truth',
  'art',
  'Plants',
  'perseverance',
  'success',
  'identity',
  'humanity',
  'wisdom',
  'resilience',
  'love',
  'nature',
  'change',
  'motivation',
  'future',
  'Music',
  'education',
  'purpose',
  'humility',
  'action',
  'growth',
  'inspiration',
  'learning',
  'legacy',
  'perspective',
  'Health',
  'happiness',
  'empowerment',
  'passion',
  'humor',
  'justice',
  'faith',
  'exploration',
  'morality',
  'compassion',
  'hope',
  'technology',
  'Movies',
  'ambition',
  'curiosity',
  'existence',
  'perception',
  'determination',
  'ethics',
  'society',
  'responsibility',
  'self-discovery',
  'progress',
  'Physics',
  'time',
  'understanding',
  'imagination',
  'equality',
  'authenticity',
  'strength',
  'integrity',
  'beauty',
  'relationships',
  'strategy',
  'Economics',
  'feminism',
  'power',
  'activism',
  'memory',
  'writing',
  'experience',
  'dreams',
  'Political Science',
  'problem-solving',
  'unity',
  'politics',
  'Observation',
  'human nature',
  'self-improvement',
  'existentialism',
  'collaboration',
  'failure',
  'impact',
  'Ocean',
  'adaptability',
  'self-awareness',
  'confidence',
  'individuality',
  'vision',
  'empathy',
  'mathematics',
  'Gaming',
  'personal growth',
  'self-reflection',
  'journey',
  'storytelling',
  'fear',
  'emotion',
  'war',
  'connection',
  'simplicity',
  'kindness',
  'Diseases and Cures',
  'character',
  'joy',
  'soul',
  'adventure',
  'acceptance',
  'service',
  'universe',
  'gratitude',
  'virtue',
  'Sports',
  'patience',
  'mystery',
  'space',
  'intellect',
  'mortality',
  'value',
  'impermanence',
  'Life Hacks (The Science Behind Them)',
  'discovery',
  'solitude',
  'mindfulness',
  'expression',
  'reflection',
  'spirituality',
  'harmony',
  'Traditions Around the World',
  'psychology',
  'struggle',
  'deception',
  'entrepreneurship',
  'awareness',
  'satire',
  'Literature',
  'self',
  'community',
  'reality',
  'wonder',
  'conservation',
  'fate',
  'language',
  'wealth',
  'adversity',
  'balance',
  'investing',
  'culture',
  'gender',
  'reason',
  'thought',
  'destiny',
  'victory',
  'space exploration',
  'Inventions',
  'AI',
  'suffering',
  'sustainability',
  'intelligence',
  'regret',
  'control',
  'Spirit',
  'Space-Time Paradoxes',
  'social justice',
  'cosmos',
  'self-worth',
  'honesty',
  'uncertainty',
  'reputation',
  'survival',
  'discipline',
  'Game Development',
  'introspection',
  'silence',
  'creation',
  'potential',
  'transience',
  'work',
  'Engineering',
  'philanthropy',
  'light',
  'influence',
  'heroism',
  'revolution',
  'critical thinking',
  'Artificial Intelligence',
  'gender equality',
  'independence',
  'AI Ethics',
  'cynicism',
  'possibility',
  'noir',
  'Peace',
  'Futurism',
  'self-control',
  'Strange Animal Behaviors',
  'self-mastery',
  'imperfection',
  'Dignity',
  'endurance',
  'choice',
  'persistence',
  'guidance',
  'interconnectedness',
  'Weird Laws',
  'diversity',
  'color',
  'rebellion',
  'metaphor',
  'law',
  'programming',
  'conscience',
  'Medical Oddities',
  'social change',
  'duty',
  'urban decay',
  'criticism',
  'meaning',
  'eternity',
  'Medical Innovations',
  'Liberty',
  'loyalty',
  'cosmic wonder',
  'Resistance',
  'irony',
  'listening',
  'World Leaders',
  'intuition',
  'hypocrisy',
  'Consciousness',
  'adaptation',
  'transformation',
  'Ancient Civilizations',
  'stoicism',
  'open-source',
  'Voice',
  'finance',
  'evolution',
  'Famous Scientists',
  'Governance',
  'rationality',
  'Holocaust',
  'branding',
  'violence',
  'wit',
  'Chemistry',
  'History',
  'inner peace',
  'Societal Impact',
  'cooperation',
  'initiative',
  'accountability',
  'Famous Battles',
  'Opportunity',
  'self-deception',
  'human spirit',
  'healing',
  'narrative',
  'fame',
  'Communication',
  'logic',
  'illusion',
  'impressionism',
  'transparency',
  'personal development',
  'Digital Ethics',
  'Fashion History',
  'disruption',
  'Mindset',
  'liberation',
  'marriage',
  'Consequences',
  'vanity',
  'Design',
  'theatre',
  'isolation',
  'Cultural Traditions',
  'inequality',
  'capitalism',
  'contentment',
  'vulnerability',
  'improvement',
  'social critique',
  'self-love',
  'Urban Legends',
  'human potential',
  'rights',
  'oppression',
  'life lessons',
  'theater',
  'Challenge',
  'Democracy',
  'conviction',
  'heritage',
  'Mind',
  'World Wars',
  'fashion',
  'enlightenment',
  'stardust',
  'human condition',
  'corruption',
  'Autonomy',
  'selflessness',
  'Archaeology',
  'inclusivity',
  'bias',
  'social commentary',
  'Colonialism',
  'contemplation',
  'Subjectivity',
  'risk management',
  'past',
  'Famous Inventors',
  'Present Moment',
  'tranquility',
  'flexibility',
  'Coexistence',
  'dialogue',
  'Pesticides',
  'inner strength',
  'Algorithmic Bias',
  'Challenges',
  'habit',
  'Military Technology',
  'aristocracy',
  'addiction',
  'gossip',
  'audience',
  'warfare',
  'censorship',
  'sorrow',
  'Mythology',
  'Energy',
  'Presence',
  'performance',
  'astrophysics',
  'Achievement',
  'Execution',
  'cosmic dance',
  'paradox',
  'class',
  'nation',
  'Inquiry',
  'Civic Duty',
  'HumanNature',
  'Diplomacy',
  'fatalism',
  'Sales',
  'secrets',
  'Thinking',
  'Famous Trials',
  'movement',
  'absurdity',
  'machines',
  'recognition',
  'Belonging',
  'Islands',
  'Human Rights',
  'aging',
  'willpower',
  'Experimentation',
  'conversation',
  'Preparation',
  'Inner Wisdom',
  'Life\'s Journey',
  'Tradition',
  'clarity',
  'self-empowerment',
  'Values',
  'alienation',
  'conformity',
  'Cosmic Mysteries',
  'Navigation',
  'Reform',
  'tech culture',
  'Practice',
  'Individualism',
  'World-building',
  'Currencies',
  'Economic Theory',
  'Ecology',
  'reading',
  'decay',
  'urban life',
  'solidarity',
  'Wilderness',
  'Human Values',
  'Biology',
  'Problem Solving',
  'agency',
  'Algorithms',
  'Industry',
  'privacy',
  'Focus',
  'cosmic origins',
  'Stillness',
  'Cryptocurrency',
  'essence',
  'causality',
  'Practicality',
  'Environmentalism',
  'self-discipline',
  'cosmic perspective',
  'Advocacy',
  'SelfDiscovery',
  'Depth',
  'Structure',
  'serenity',
  'purity',
  'pride',
  'crime',
  'honor',
  'Meteorology',
  'Information',
  'heart',
  'Human Emotion',
  'Fantasy',
  'guilt',
  'landscape',
  'betrayal',
  'Future of AI',
  'Folklore',
  'environmental stewardship',
  'Vastness',
  'Computation',
  'duality',
  'Digital Rights',
  'Data',
  'Motive',
  'microcosm',
  'comedy',
  'Retro Games',
  'Unknown',
  'memories',
  'appearances',
  'Oneness',
  'Sovereignty',
  'foundation',
  'Seasons',
  'moment',
  'Citizenship',
  'Neuroscience',
  'access',
  'Building',
  'collective action',
  'appreciation',
  'Self-expression',
  'hidden narratives',
  'Detection',
  'Quantum Mechanics',
  'apathy',
  'AI Governance',
  'England',
  'Mastery',
  'Effort',
  'longing',
  'Internet History',
  'certainty',
  'ProblemSolving',
  'Prejudice',
  'hardship',
  'Revelation',
  'ingenuity',
  'Aviation',
  'technique',
  'ownership',
  'Social Impact',
  'Women\'s Rights',
  'Perfection',
  'senses',
  'Sea Wisdom',
  'Everyday Objects (Their History)',
  'distrust',
  'competitive advantage',
  'Artistry',
  'stellar legacy',
  'precision',
  'Civilization',
  'Skepticism',
  'hardboiled',
  'Risk',
  'Geography',
  'Social Injustice',
  'Government',
  'dark humor',
  'Dedication',
  'lessons',
  'Business Strategy',
  'fragility',
  'Authority',
  'Detail',
  'Historical Events',
  'appearance',
  'Insight',
  'grief',
  'paranoia',
  'AIResponsibility',
  'flow',
  'Pain',
  'Robotics',
  'Diligence',
  'product-market fit',
  'iteration',
  'judgment',
  'biodiversity',
  'Ignorance',
  'inner-strength',
  'Emotions',
  'Uniqueness',
  'alcohol',
  'Composition',
  'cosmic paradoxes',
  'Cultural Impact',
  'Propaganda',
  'Romance',
  'InnerWorld',
  'Revolutions',
  'Cultural Ethos',
  'Foundational Principles',
  'theatrical life',
  'Human-AI',
  'Divine Unity',
  'Gender Roles',
  'Vigilance',
  'founder psychology',
  'forgotten light',
  'cosmic poetry',
  'imagination and science',
  'Historic Crimes',
  'Indifference',
  'Ecosystems',
  'pessimism',
  'artistic expression',
  'bodily autonomy',
  'Stage',
  'celestial time',
  'Conquest',
  'Naval History',
  'Inner Life',
  'metaverse governance',
  'enemy assessment',
  'analytics',
  'elegance',
  'African Spirit',
  'Religion',
  'digital sovereignty',
  'Societal Expectation',
  'ancient echoes',
  'equity',
  'Environmental Science',
  'decentralized ethics',
  'quiet revelation',
  'Synchronous Thriving',
  'behavioral economics',
  'Prevention',
  'Scientific Method',
  'counsel',
  'AI Responsibility',
  'feminist thought',
  'Recession',
  'Food',
  'InnerPeace',
  'streetlife',
  'Future of Sapience',
  'Future of Work',
  'Self-Reliance',
  'Inner Truth',
  'Surprise',
  'detachment',
  'Awe',
  'pursuit',
  'Climate Change',
  'despair',
  'Proactiveness',
  'social responsibility',
  'rhythm',
  'Self-overcoming',
  'constancy',
  'scientific integrity',
  'Genetics',
  'Ethical AI',
  'Totalitarianism',
  'urban_life',
  'self-sabotage',
  'science-fantasy',
  'Intuitive Design',
  'invisibility',
  'Georgian society',
  'Transportation',
  'Sacrifice',
  'Loss',
  'Employee Welfare',
  'residual energy',
  'AI Maintenance',
  'Fearlessness',
  'Lifelong Learning',
  'inner turmoil',
  'Customer Experience',
  'Decolonization',
  'ephemeral',
  'early adopters',
  'Co-creative Technologies',
  'emancipation',
  'collective unconscious',
  'Order',
  'Details',
  'ancestors',
  'alternative cartography',
  'human-AI collaboration',
  'Demand Management',
  'Famous Landmarks',
  'hidden beauty',
  'Showmanship',
  'CosmicSagas',
  'zen',
  'Strangeness',
  'dreamers',
  'Renewal',
  'Time Travel (Theories)',
  'cosmic library',
  'Existential Risk',
  'Civil Rights',
  'Human Liberties',
  'Transcendence',
  'Doubt',
  'poetic science',
  'Construction',
  'Empathetic AI',
  'questions in the dark',
  'cosmic silence',
  'Caves and Mountains',
  'Co-evolution',
  'triumphs',
  'animal welfare',
  'Inner World',
  'Tides',
  'artistic process',
  'moral philosophy',
  'writing craft',
  'human_nature',
  'interstellar travel',
  'Sustainable Development',
  'Human Flourishing',
  'crime fiction',
  'dialectics',
  'atmosphere',
  'Clues',
  'social norms',
  'Machine Ethics',
  'Engineering Feats',
  'customer-centric',
  'proactive ethics',
  'light and absence',
  'Symbiotic Future',
  'ephemeral beauty',
  'CosmicDust',
  'epic scale',
  'desperation',
  'decision making',
  'Languages of the World',
  'Self-knowledge',
  'soulful-journeys',
  'Nazi Regime',
  'Molecular Structure',
  'Philosophy of AI',
  'DigitalHumanism',
  'Environment',
  'season',
  'Dreams and Sleep',
  'cosmic wisdom',
  'unseen patterns',
  'Übermensch',
  'exclusion',
  'Ethical Sustainability',
  'HiddenStories',
  'Generosity',
  'Animal Spirits',
  'Sea',
  'Paleontology',
  'Bias Recognition',
  'Nursing',
  'Employment',
  'Weakness',
  'business intelligence',
  'mockery',
  'Market Failure',
  'symbiosis',
  'Bizarre Historical Mishaps',
  'FutureEthics',
  'myth',
  'Everyday Life',
  'The Other',
  'Ocean\'s Embrace',
  'Precaution',
  'symphony',
  'apoliticism',
  'Leisure',
  'Unexplained Phenomena',
  'Power of Ideas',
  'Patterns',
  'Collective Power',
  'Natural Selection',
  'riches',
  'Divine Purpose',
  'Freedom of Thought',
  'System Design',
  'Social Construction',
  'Short Run',
  'Board Games',
  'AI Emotional Simulation',
  'secrecy',
  'reproductive rights',
  'Human-AI Interaction',
  'divine will',
  'startup culture',
  'Possibilities',
  'MundaneMagic',
  'self acceptance',
  'invisible worlds',
  'Rivers and Lakes',
  'Ethical Development',
  'Autonomous Ethics',
  'mental toughness',
  'power dynamics',
  'AI Development',
  'personal narrative',
  'Suffrage',
  'Status',
  'Vaccines',
  'new worlds',
  'Technological Empowerment',
  'self-realization',
  'TeamBuilding',
  'Metrics',
  'DecisionMaking',
  'Societal Reflection',
  'wholeness',
  'Time Zones',
  'Exposure',
  'SyntheticConsciousness',
  'CosmicWisdom',
  'Inner Compass',
  'Superintelligence',
  'Inclusion',
  'Disillusionment',
  'Human Consciousness',
  'SocietalImpact',
  'Astronomy',
  'Monarchy',
  'Global Challenges',
  'cosmic shadows',
  'Trust',
  'Value Creation',
  'social manipulation',
  'Extravagance',
  'human connection to the universe',
  'peacebuilding',
  'Regulation',
  'Future Intelligence',
  'Writing Systems',
  'Electromagnetism',
  'data-driven decisions',
  'Economic Psychology',
  'celestial wonder',
  'CompetitiveAdvantage',
  'data-driven',
  'Freedom of Speech',
  'Optimization',
  'cosmic artistry',
  'unseen galaxies',
  'Animals',
  'erasure',
  'cosmic harmony',
  'natural philosophy',
  'HumanSoul',
  'moral humility',
  'infinity',
  'time\'s tapestry',
  'Nature\'s Endurance',
  'Chaos',
  'self_discovery',
  'Endangered Species',
  'scientific imagination',
  'restraint',
  'Dignity in Automation',
  'Manipulation',
  'self-destruction',
  'user behavior',
  'art and science',
  'World Religions',
  'International Relations',
  'Education Reform',
  'Revaluation of values',
  'PhilosophyOfAI',
  'creative process',
  'Choices',
  'scalability',
  'AIEthics',
  'psyche',
  'artistic vision',
  'heartbreak',
  'Oceanography',
  'character building',
  'platform',
  'stoic-practice',
  'deceit',
  'Gradualism',
  'cosmic stories',
  'Global Unity',
  'Effectiveness',
  'Misunderstanding',
  'Global Impact',
  'Non-violence',
  'Work Ethic',
  'scaling',
  'Seafaring Spirit',
  'Demand',
  'Self-determination',
  'HiddenBeauty',
  'Coral Reefs',
  'Human Machine Collaboration',
  'natural order',
  'African Voice',
  'everyday magic',
  'Evidence',
  'InnerLife',
  'Nonviolence',
  'psychological',
  'meteorites',
  'Deserts',
  'Invention',
  'national identity',
  'AI Trust',
  'human-computer interaction',
  'Company Culture',
  'time and memory',
  'effortless action',
  'starlight',
  'Inner conflict',
  'symbols',
  'operational efficiency',
  'Digital Anthropology',
  'debt',
  'life_lessons',
  'Ego',
  'AlgorithmicBias',
  'Tolerance',
  'ethical coexistence',
  'Famous Pirates',
  'CosmicConnection',
  'ecosystem',
  'InnerSpace',
  'CosmicHistory',
  'AIJustice',
  'Children',
  'cosmic imagination',
  'voyage',
  'Dinosaurs',
  'Brand Building',
  'Expedition',
  'climate tech',
  'AI Narratives',
  'folly',
  'Social Reform',
  'moonshot thinking',
  'inner light',
  'Inner Fortitude',
  'Self-Actualization',
  'social hierarchy',
  'Bioluminescence',
  'Gift',
  'molecular biology',
  'self discovery',
  'invisible forces',
  'maritime',
  'sisterhood',
  'decentralization',
  'existential dust',
  'Helpfulness',
  'character development',
  'Calendars and Time',
  'AI Rights',
  'First Principles',
  'community building',
  'patriarchy',
  'State of Nature',
  'AI sentience',
  'co-creation',
  'Societal Critique',
  'Modernism',
  'Famous Books',
  'manners',
  'Pioneer',
  'Goodness',
  'Self-Renewal',
  'Fanaticism',
  'UrbanLife',
  'Statistics',
  'Human Anatomy',
  'quantum ethics',
  'MoralAgency',
  'scientific truth',
  'emotional resonance',
  'Social Satire',
  'Epistemology',
  'Social Contract',
  'environmental solutions',
  'experiential learning',
  'Dogma',
  'human frailty',
  'Humanity\'s Greatest Achievements',
  'Grandeur',
  'Modernity',
  'songwriting',
  'DataAnalytics',
  'personal-growth',
  'human cosmic connection',
  'Laissez-faire',
  'Famous Paintings',
  'continuous improvement',
  'founder mindset',
  'market disruption',
  'Mysteries',
  'Code Ethics',
  'wildlife conservation',
  'artistic voice',
  'Everyday',
  'techno-ecology',
  'Injustice',
  'Space Missions',
  'technological advancements',
  'Protection',
  'Ethical Design',
  'Digital Transparency',
  'the deep',
  'HumanValues',
  'Wonders of the World',
  'Inner-fortress',
  'SelfReflection',
  'cosmology',
  'karma',
  'Nature\'s Mysteries',
  'Emergence',
  'Self-Governance',
  'self-guidance',
  'Social Progress',
  'growth hacking',
  'Social Media',
  'future-proofing morality',
  'Inner Music',
  'Labor Rights',
  'Ethical Decision-making',
  'AIIntegration',
  'self-deprecation',
  'social strategy',
  'intimacy',
  'Leviathan',
  'Iconic Buildings',
  'data analysis',
  'Good vs Evil',
  'FutureOfHumanity',
  'Fields',
  'data analytics',
  'Just AI',
  'Economic Stimulus',
  'Emotional Intelligence',
  'pretension',
  'The Human Brain',
  'Pragmatism',
  'AI Bias',
  'structure-function',
  'surrealism',
  'EthicalDesign',
  'Music Theory',
  'Data Ethics',
  'black holes',
  'Cycles',
  'wordplay',
  'Continents',
  'sound of the universe',
  'Will to power',
  'Well-being',
  'astronomical artistry',
  'Economic Policy',
  'possession',
  'DigitalRights',
  'God is dead',
  'Individual Action',
  'Ancestry',
  'startup strategy',
  'Crystallography',
  'rhetoric',
  'inner-peace',
  'Efficiency',
  'The Solar System',
  'soulful-living',
  'Difference',
  'Moral AI',
  'Homecoming',
  'ResponsibleAI',
  'hubris',
  'Proactive Governance',
  'lightness',
  'dawn',
  'Volcanoes',
  'Functionality',
  'Human Intellect',
  'divine calling',
  'Nature\'s Power',
  'drama',
  'astronomical metaphors',
  'Moral Courage',
  'Quality',
  'Empire',
  'origins',
  'maritime-philosophy',
  'Memes (History)',
  'Skill',
  'Time Management',
  'marginalized voices',
  'Selfhood',
  'Future Generations',
  'cosmic art',
  'Crisis Management',
  'hard-boiled',
  'Night',
  'Esports',
  'Human Machine Interaction',
  'condemnation',
  'gardens',
  'Personhood',
  'individuation',
  'modern art',
  'symmetry',
  'Prudence',
  'Tyranny',
  'Natural Disasters',
  'Care',
  'Peacekeeping',
  'ephemeral evidence',
  'cosmic guidance',
  'AI Values',
  'Human Dignity',
  'Integration',
  'Common Good',
  'Technological Stewardship',
  'Nutrition',
  'tact',
  'inner journey',
  'Human Purpose',
  'Automation',
  'Stewardship',
  'luminescence',
  'Deep Sea',
  'pulp fiction',
  'Space Technology',
  'Digital Age',
  'cosmic identity',
  'Self-Interest',
  'AI Policy',
  'free will',
  'Business Ethics',
  'national greatness',
  'absence',
  'Modesty',
  'Rare Animals',
  'LifeJourney',
  'social masks',
  'oceanic-philosophy',
  'Government Intervention',
  'X-ray crystallography',
  'Philology',
  'Human Impact',
  'cosmic exploration',
  'gravitational harmony',
  'Hackers and Hacking',
  'Manhood',
  'boldness',
  'cold',
  'childhood',
  'spiritual growth',
  'Drive',
  'Competition',
];
